# Generated by Django 5.0.6 on 2024-06-24 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_capteur', models.CharField(db_column='NomCapteur', max_length=255, unique=True)),
                ('piece', models.CharField(db_column='Piece', max_length=255)),
                ('emplacement', models.CharField(blank=True, db_column='Emplacement', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Capteurs',
            },
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('donnee_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Timestamp')),
                ('valeur', models.CharField(db_column='Valeur', max_length=255)),
                ('capteur', models.ForeignKey(db_column='CapteurID', on_delete=django.db.models.deletion.CASCADE, to='myapp.capteur')),
            ],
            options={
                'db_table': 'Donnees',
            },
        ),
    ]
